# Generated by Django 4.0.3 on 2022-04-09 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connectBill', '0003_alter_user_options_user_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignerPopol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectBill.user')),
            ],
        ),
    ]
