# Generated by Django 4.0.4 on 2022-05-04 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SearchDesignerApi', '0001_initial'),
        ('usersApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerpopol',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersApi.designer'),
        ),
    ]
