# Generated by Django 4.0.3 on 2022-04-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchDesignerApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designerpopol',
            options={'verbose_name': '포트폴리오'},
        ),
        migrations.RenameField(
            model_name='designerpopol',
            old_name='body',
            new_name='description',
        ),
        migrations.AddField(
            model_name='designerpopol',
            name='portfolio_image',
            field=models.ImageField(null=True, upload_to='SearchDesignerApi'),
        ),
        migrations.AddField(
            model_name='designerpopol',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterModelTable(
            name='designerpopol',
            table='Portfolio',
        ),
    ]
