# Generated by Django 4.0.3 on 2022-04-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchDesignerApi', '0002_alter_designerpopol_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designerpopol',
            name='portfolio_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='designerpopol',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
