# Generated by Django 4.0.3 on 2022-04-14 06:18

import SearchDesignerApi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchDesignerApi', '0003_alter_designerpopol_portfolio_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designerpopol',
            name='portfolio_image',
            field=models.ImageField(null=True, upload_to=SearchDesignerApi.models.path_and_rename),
        ),
    ]
