# Generated by Django 3.2.13 on 2022-05-10 22:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usersApi', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
