# Generated by Django 4.0.4 on 2022-05-09 11:19

from django.db import migrations, models
import userReview.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review_title', models.CharField(max_length=200)),
                ('Review_Image', models.ImageField(upload_to=userReview.models.path_and_rename)),
                ('customer_id', models.IntegerField(null=True)),
                ('Review_description', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'customerReview',
            },
        ),
    ]
