# Generated by Django 4.0.4 on 2022-05-26 14:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import userReview.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_commission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('small_image', models.ImageField(upload_to=userReview.models.path_and_rename)),
                ('panorama_image', models.ImageField(upload_to=userReview.models.path_and_rename)),
                ('designer_id', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('title', models.CharField(blank=True, default=None, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Commission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_commission.commission')),
            ],
            options={
                'verbose_name': 'customerReview',
            },
        ),
    ]
