# Generated by Django 4.0.4 on 2022-06-02 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_review_designerreview_review_text'),
        ('userReview', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreview',
            name='designer_id',
        ),
        migrations.AddField(
            model_name='customerreview',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.designer'),
        ),
    ]
