# Generated by Django 4.0.4 on 2022-06-02 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userReview', '0003_remove_customerreview_designer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerreview',
            old_name='Commission',
            new_name='commission',
        ),
    ]
