# Generated by Django 4.0.5 on 2022-06-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='average_stars',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
