# Generated by Django 4.0.4 on 2022-05-31 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_commission', '0003_remove_commission_messageflag'),
        ('users', '0002_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='designer',
            name='prccessing_commission_id',
        ),
        migrations.CreateModel(
            name='ProcessingCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_commission.commission')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.designer')),
            ],
        ),
    ]
