# Generated by Django 4.0.4 on 2022-06-02 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_client_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designerreview',
            old_name='review',
            new_name='review_text',
        ),
    ]
