# Generated by Django 4.0.4 on 2022-06-02 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_commission', '0007_alter_commission_commission_image'),
        ('users', '0005_rename_review_designerreview_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerreview',
            name='commission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_commission.commission'),
        ),
        migrations.DeleteModel(
            name='ProcessingCommission',
        ),
    ]
