# Generated by Django 4.0.3 on 2022-04-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectBill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('admin', 'admin_member'), ('designer', 'designer_member'), ('client', 'client')], max_length=8),
        ),
    ]
