# Generated by Django 4.0.3 on 2022-04-09 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectBill', '0002_alter_user_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_image', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=300)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectBill.user')),
            ],
            options={
                'verbose_name': '포트폴리오',
                'db_table': 'Portfolio',
            },
        ),
    ]
