# Generated by Django 4.0.3 on 2022-04-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectBill', '0002_alter_user_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='SearchDesignerApi'),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
