# Generated by Django 4.0.4 on 2022-05-23 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerpopol',
            name='designer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.designer'),
        ),
        migrations.AddField(
            model_name='designerpopol',
            name='projects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.projects'),
        ),
    ]
