# Generated by Django 4.0.4 on 2022-05-31 11:56

from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='small_image',
            field=models.ImageField(blank=True, upload_to=portfolio.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='projects',
            name='portfolio',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.designerpopol'),
        ),
    ]
