# Generated by Django 4.0.4 on 2022-06-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_projects_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='participation_date',
            field=models.CharField(max_length=100),
        ),
    ]
