# Generated by Django 4.0.3 on 2022-05-31 08:37

import client_commission.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_id', models.IntegerField(blank=True, null=True)),
                ('small_image', models.ImageField(null=True, upload_to=client_commission.models.path_and_rename)),
                ('commission_image', models.ImageField(null=True, upload_to=client_commission.models.path_and_rename)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(null=True)),
                ('budget', models.IntegerField()),
                ('finish_date', models.IntegerField()),
                ('deadline', models.CharField(max_length=50)),
                ('current_status', models.IntegerField(blank=True, choices=[(0, 'Not Started'), (1, 'Not Started Not Selected'), (2, 'Proceeding'), (3, 'Finished')], default=0)),
                ('messageFlag', models.BooleanField(blank=True, default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Commission',
            },
        ),
        migrations.CreateModel(
            name='RequestedDesigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_designer', to='client_commission.commission')),
            ],
        ),
    ]
