# Generated by Django 4.0.4 on 2022-05-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_commission', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='messageFlag',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='commission',
            name='request_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='commission',
            name='request_designer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
