# Generated by Django 4.0.3 on 2022-05-31 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_commission', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='messageFlag',
        ),
    ]
