# Generated by Django 4.0.4 on 2022-05-31 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_client_options_and_more'),
        ('client_commission', '0003_remove_commission_messageflag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='designer_id',
        ),
        migrations.AddField(
            model_name='commission',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.designer'),
        ),
    ]
