# Generated by Django 4.0.4 on 2022-05-30 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_designerreview'),
        ('client_commission', '0004_remove_commission_status_commission_current_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='request_designer_id',
        ),
        migrations.CreateModel(
            name='RequestedDesigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_designer', to='client_commission.commission')),
                ('designer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.designer')),
            ],
        ),
    ]
