# Generated by Django 4.0.4 on 2022-06-01 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_projects_description'),
        ('client_commission', '0005_requesteddesigner_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesteddesigner',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.designerpopol'),
        ),
    ]
