# Generated by Django 4.0.4 on 2022-06-02 11:22

import client_commission.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_commission', '0006_requesteddesigner_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='commission_image',
            field=models.FileField(null=True, upload_to=client_commission.models.path_and_rename),
        ),
    ]
